# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-04 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFirst',
            fields=[
                ('mf_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mf_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ModelSecond',
            fields=[
                ('ms_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ms_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ModelMain',
            fields=[
                ('modelsecond_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='multipleapp.ModelSecond')),
                ('modelfirst_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multipleapp.ModelFirst')),
                ('mm_name', models.CharField(max_length=30)),
            ],
            bases=('multipleapp.modelfirst', 'multipleapp.modelsecond'),
        ),
    ]
