# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-04 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30)),
                ('sal', models.IntegerField()),
                ('loc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmpProxy',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('proxyapp.employee',),
        ),
    ]
