# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-04 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cfee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multitableapp.Course')),
                ('sname', models.CharField(max_length=30)),
                ('sage', models.IntegerField()),
            ],
            bases=('multitableapp.course',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multitableapp.Student')),
                ('tname', models.CharField(max_length=30)),
                ('temail', models.EmailField(max_length=254)),
            ],
            bases=('multitableapp.student',),
        ),
    ]
